### ISSUE TITLE
Upgrade to 3.0.0-M3

### ISSUE THREAD

**Issue by jilen** [lampepfl/dotty-macro-examples#11]
Seems quite a lot staff changed in `3.0.0-M3`

**Comment by timzaak** [comment]
can not run with 3.0.0-RC1

**Comment by timzaak** [comment]
https://github.com/YuriyMazepin/dotty-macro-examples/pull/1
fixed  3.0.0-RC1, except the example `macroTypeclassDerivation`

**Comment by ShapelessCat** [comment]
@timzaak
