### ISSUE TITLE
Instantiate a class from a Map

### ISSUE THREAD

**Issue by gekomad** [lampepfl/dotty-macro-examples#16]
May you add the example: instantiate a class from a Map

```scala
    case class Foo(a: Int, c: String)
    val params: Map[String, String] = Map("a" -> "1", "c" -> "hi")
    fromParams[Foo](params) // Right(Foo(1, "hi")))
```

**Comment by anatoliykmetyuk** [comment]
The classic application of this mechanics if typeclass derivation. Rather than using a custom macro, I suggest using the [Mirror API](https://docs.scala-lang.org/scala3/reference/contextual/derivation.html) or [Shapeless](https://github.com/typelevel/shapeless-3).
