### ISSUE TITLE
A ternary operator example wanted

### ISSUE THREAD

**Issue by plokhotnyuk** [lampepfl/dotty-macro-examples#8]
Could it be possible with Dotty to write some macro for ternary operator that would replace
```
A ? B : C
```
by
```
if (A)
  B
else
  C
```
without adding an overhead in runtime?

**Comment by anatoliykmetyuk** [comment]
I don't believe this is possible. Expressions passed to the macros need to be able to typecheck. Therefore, it's not possible to modify Scala syntax using macros.
