### ISSUE TITLE
nice to have example

### ISSUE THREAD

**Issue by aappddeevv** [lampepfl/dotty-macro-examples#9]
It would be nice to have an example where a macro runs inside a function, but it returns a tuple of the function name and an Object that has the parameters as vals and the parameter values as typed values.

```scala
def blah(x: Int, y: String, z: Float) =
  val (name, params) = functionMacro
  println("x value in function $name is ${params.x}")
```

**Comment by frobinet** [comment]
@anatoliykmetyuk Is this even doable using Scala 3 macros?

**Comment by anatoliykmetyuk** [comment]
I believe [lihaoyi/sourcecode](https://github.com/lihaoyi/sourcecode) does the job, and it is ported to Scala 3.

**Comment by aappddeevv** [comment]
That's fair.
